package com.springbasics.springin5steps;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;

import com.springbasics.springin5steps.basic.BinarySearchImpl;

@SpringBootApplication // Automatically scans the package and the sub-package
public class SpringIn5StepsBasicApplication {

	// What are the beans?
	// What are the dependencies of a bean?
	// What to search for beans? No need to do this because of the same package

	public static void main(String[] args) {

		// BinarySearchImpl binarySearch = new BinarySearchImpl(new
		// BubbleSortAlogorithm()); -->This is generated by Spring
		// Application Context maintains all the beans

		ApplicationContext applicationContext = SpringApplication.run(SpringIn5StepsBasicApplication.class, args);

		BinarySearchImpl binarySearch = applicationContext.getBean(BinarySearchImpl.class);

		BinarySearchImpl binarySearch1 = applicationContext.getBean(BinarySearchImpl.class);

		System.out.println(binarySearch);
		System.out.println(binarySearch1);

		int result = binarySearch.binarySearch(new int[] { 10, 5, 2 }, 2);
		System.out.println(result);
	}

}
